#pragma once

// TCICT skip macros for unimplemented functions.
//
// Default: all tests are enabled (no skipping).
// Backends define these to skip specific tests for unimplemented functions.
//
// Usage in backend CMakeLists.txt:
//   target_compile_definitions(my_tests PRIVATE
//       TCICT_SKIP_QR
//       TCICT_SKIP_LQ
//   )
//
// Available skip macros:
//
// Construction:
//   TCICT_SKIP_ALLOCATE, TCICT_SKIP_ZEROS, TCICT_SKIP_FILL, TCICT_SKIP_EYE,
//   TCICT_SKIP_RANDOM, TCICT_SKIP_ASSIGN_FROM_RANGE, TCICT_SKIP_COPY,
//   TCICT_SKIP_MOVE, TCICT_SKIP_CLEAR
//
// Read-only getters:
//   TCICT_SKIP_ORDER, TCICT_SKIP_SHAPE, TCICT_SKIP_SIZE, TCICT_SKIP_SIZE_BYTES,
//   TCICT_SKIP_GET_ELEM
//
// Tensor manipulation:
//   TCICT_SKIP_SET_ELEM, TCICT_SKIP_RESHAPE, TCICT_SKIP_TRANSPOSE,
//   TCICT_SKIP_CPLX_CONJ, TCICT_SKIP_TO_CPLX, TCICT_SKIP_REAL, TCICT_SKIP_IMAG,
//   TCICT_SKIP_EXPAND, TCICT_SKIP_SHRINK, TCICT_SKIP_EXTRACT_SUB,
//   TCICT_SKIP_REPLACE_SUB, TCICT_SKIP_CONCATENATE, TCICT_SKIP_STACK,
//   TCICT_SKIP_FOR_EACH, TCICT_SKIP_FOR_EACH_WITH_COORS
//
// Linear algebra:
//   TCICT_SKIP_DIAG, TCICT_SKIP_NORM, TCICT_SKIP_NORMALIZE, TCICT_SKIP_SCALE,
//   TCICT_SKIP_TRACE, TCICT_SKIP_EXP, TCICT_SKIP_INVERSE, TCICT_SKIP_CONTRACT,
//   TCICT_SKIP_LINEAR_COMBINE, TCICT_SKIP_SVD, TCICT_SKIP_TRUNC_SVD,
//   TCICT_SKIP_QR, TCICT_SKIP_LQ, TCICT_SKIP_EIGVALS, TCICT_SKIP_EIGVALSH,
//   TCICT_SKIP_EIG, TCICT_SKIP_EIGH
//
// I/O:
//   TCICT_SKIP_SAVE, TCICT_SKIP_LOAD
//
// Miscellaneous:
//   TCICT_SKIP_TO_RANGE, TCICT_SKIP_SHOW, TCICT_SKIP_CLOSE, TCICT_SKIP_CONVERT,
//   TCICT_SKIP_VERSION
